### PR TITLE
Uber Command Line Interface

### PR DESCRIPTION
**Pull request by Mulkave**
Introduces `uberc` - a command-line interface to be used to configure and analyze without having to edit files or code.

This executable includes two commands
- `uberc config` will prompt for (with fair defaults when applicable)
  - `username`
  - `password`
  - `crawled data storage path`
  - `parsed data storage path`

- `uberc analyze` will generate analysis files

### CODE REVIEW

**Comment by Link-** [comment]
Great addition @Mulkave! Love it.
Do you mind if I keep this in the future release (alpha-0.2.2) instead of 0.2.1?

**Comment by Mulkave** [comment]
Totally cool, it's yours now 😄

**Comment by Link-** [comment]
We also need to write the unit tests for this addition.

**Comment by Link-** [comment]
Merged with alpha-0.2.2

```
Merge: 9fc1ca6 4bc6404
Author: Bassem Dghaidi <bassem@interop.link>
Date:   Sat Jun 18 13:21:06 2016 +0300

    Merge branch 'mulkwave-pr-170616' into alpha-0.2.2

    * mulkwave-pr-170616:
      indentation tweaks in README
      add some informative messages
      add CLI usage instructions to README
      move uberc executable to ./bin
      implement "config" and "analyze" commands
      require symfony/console

    # Conflicts:
    #       README.md
```

**Comment by Mulkave** [comment]
True. Sorry for not to shipping with tests, wanted to have it out a.s.a.p. Should be simple to test though.

**Comment by Link-** [comment]
No worries @Mulkave I'll write them. I introduced some changes as well, you can find them in the branch alpha-0.2.2

**Pull request closed without merging**
